#NUMERO DE DISPOSITIVOS (Y MISSING)
#NUMERO DE ALERTAS
#MEDIA Y DESVIACION ESTANDAR DEL TOTAL DE PUERTOS ABIERTOS
#MEDIA Y DESVIACION ESTANDAR DEL NUMERO DE VULNERABILIDADES DETECTADAS
#VALOR MINIMO Y MAXIMO DEL TOTAL DE PUERTOS ABIERTOS
#VALOR MINIMO Y MAXIMO DEL NUMERO DE VULNERABILIDADES DETECTADAS